[app]
service_name = "Arkan-Poseidon"
version      = "0.1.0"
debug        = true

[poseidon]
login_port = 6900
char_port  = 6121
ro_port    = 5121

[openkore]
host = "127.0.0.1"
port = 5293

[protocol]
max_packet = 4194304    # 4 MiB

[query]
max_buf = 1048576       # 1 MiB

[net]
max_write_queue = 1024
tcp_nodelay = true
tcp_keepalive = true

[log]
level = "info"
to_file = false
file = "logs/poseidon.log"
max_files = 3
max_size_bytes = 2097152

[dummy_char]
name = "Novice"
map  = "new_zone01"
x    = 53
y    = 111
