[app]
service_name = "Thanatos"
version      = "0.1.2"
debug        = true

[thanatos]
ro_host = "127.0.0.1"
login_port = 6900
char_port  = 6121

[protocol]
max_packet = 4194304    # 4 MiB

[query]
max_buf = 1048576       # 1 MiB

[net]
query_host = "127.0.0.1"
query_port = 24395
max_write_queue = 1024
tcp_nodelay = true
tcp_keepalive = true

[log]
level = "info"
to_file = false
file = "logs/thanatos.log"
max_files = 3
max_size_bytes = 2097152
